name: 'Git Commit ID Generator'
description: 'Generate and return a new tag based on the last tag and the commit ID'
author: 'Bradley Goulding'
inputs:
  include_repo_name:
    description: 'Include repository name in version string'
    required: false
    default: 'false'
outputs:
  version_string:
    description: 'The version string to use for the current commit'
    value: ${{ steps.version_string.outputs.version_string }}
  latest_tag:
    description: 'The latest tag'
    value: ${{ steps.latest_tag.outputs.latest_tag }}
  commits_since_tag:
    description: 'The number of commits since the latest tag'
    value: ${{ steps.commits_since_tag.outputs.commits_since_tag }}
  short_commit_hash:
    description: 'The short commit hash'
    value: ${{ steps.short_commit_hash.outputs.short_commit_hash }}
runs:
  using: "composite"
  steps:
    - name: Get Latest Tag
      shell: bash
      id: latest_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

    - name: Get Number of Commits Since Latest Tag
      shell: bash
      id: commits_since_tag
      run: |
        commits_since_tag=$(git rev-list ${{ steps.latest_tag.outputs.latest_tag }}..HEAD --count)
        echo "commits_since_tag=$commits_since_tag" >> $GITHUB_OUTPUT

    - name: Get Short Commit Hash
      shell: bash
      id: short_commit_hash
      run: |
        short_commit_hash=$(git rev-parse --short HEAD)
        echo "short_commit_hash=$short_commit_hash" >> $GITHUB_OUTPUT

    - name: Create Version String
      shell: bash
      id: version_string
      run: |
        latest_tag="${{ steps.latest_tag.outputs.latest_tag }}"
        commits_since_tag="${{ steps.commits_since_tag.outputs.commits_since_tag }}"
        short_commit_hash="${{ steps.short_commit_hash.outputs.short_commit_hash }}"
        version_string="${latest_tag}-${commits_since_tag}-g${short_commit_hash}" 
        if [[ "${{ inputs.include_repo_name }}" == 'true' ]]; then
          org_repo="${{ github.repository }}"
          version_string="${org_repo}:${version_string}"
        fi
        echo "version_string=$version_string" >> $GITHUB_OUTPUT

    - name: Display Version String
      shell: bash
      id: echo_version_string
      run: |
        echo "Version String: ${{ steps.version_string.outputs.version_string }}"